---
- hosts: kubemasters
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: /root
        creates: cluster_initialized.txt

    - name: Create .kube directory for admin user
      file:
        path: "~/.kube"
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "~/.kube/config"
        remote_src: yes

    - name: Install Flannel Pod network
      shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml >> pod_network_setup.txt 
      args:
        chdir: /root
        creates: pod_network_setup.txt

    - name: Create join token
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command as fact
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: kubenodes
  become: yes
  tasks:
    - name: Join the cluster
      shell: "{{ hostvars[groups['kubemasters'][0]].join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
