---
- hosts: kubemasters
  become: yes
  tasks:
    - name: Retrieve Helm 3 binary archive
      unarchive:
        src: https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes
        creates: /usr/local/bin/helm

    - name: Move Helm binary into place
      command: cp /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Add Prometheus chart repo
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm repos
      command: helm repo update

    - name: Install Prometheus Operator via Helm 3
      command: >
        helm install prometheus-stack prometheus-community/kube-prometheus-stack
        --set grafana.enabled=true
        --create-namespace --namespace monitoring
